DECLARE
	v_count NUMBER;
BEGIN
	INSERT INTO DEPT VALUES(99, 'PROVISIONAL', 'PROVISIONAL');
	COMMIT;
	
	SELECT COUNT (*) INTO v_count FROM emp WHERE DEPTNO = 20;
	
	UPDATE emp SET DEPTNO = 99 WHERE DEPTNO = 20;
	
	DELETE FROM DEPT WHERE DEPTNO = 20;
	
	DBMS_OUTPUT.PUT_LINE('USUARIOS ELIMINADOS: '|| v_count);
END;
/
